
auto_offset_reset: "earliest"
boostrap_servers: "b-1.brokerbean.o32r3r.c16.kafka.us-east-1.amazonaws.com:9092,b-2.brokerbean.o32r3r.c16.kafka.us-east-1.amazonaws.com"
db_host: "ncc-1701-a.c5h6quudb39v.us-east-1.rds.amazonaws.com"
db_name: "room_n_board"
group_id: "reckoning"
topic: "rooms-v1"
